apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  namespace: event-driven
spec:
  selector:
    app: event-driven-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30007
  type: NodePort

