stages:
  - build

build-and-push:
  stage: build
  image: maven:3.9.6-eclipse-temurin-17
  script:
    - mvn compile com.google.cloud.tools:jib-maven-plugin:build
      -Dimage=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      -Djib.to.auth.username$CI_REGISTRY_USER
      -Djib.to.auth.password=$CI_REGISTRY_PASSWORD
  only:
    - main